# Generated by Django 4.2.7 on 2023-12-22 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utiles.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('image', models.ImageField(upload_to='profile/', verbose_name='Image')),
                ('code', models.CharField(default=utiles.generate_code.genrate_code, max_length=50, verbose_name='Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Secondary', 'Secondary'), ('Primary', 'Primary')], max_length=50, verbose_name='Title')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Busseniss', 'Busseniss'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=50, verbose_name='Title')),
                ('address', models.PositiveIntegerField(verbose_name='Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
