# Generated by Django 4.2.7 on 2023-11-26 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utiles.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utiles.generate_code.genrate_code, max_length=50, verbose_name='Id')),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utiles.generate_code.genrate_code, max_length=50, verbose_name='Id')),
                ('status', models.CharField(choices=[('recived', 'recived'), ('processed', 'processed'), ('shipped', 'shipped'), ('delevered', 'delevered')], max_length=50, verbose_name='Status')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order_time')),
                ('delevery_time', models.DateField(blank=True, null=True, verbose_name='Delevery_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quntity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_order', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quntity')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='orders.cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cart', to='products.products')),
            ],
        ),
    ]
