# Generated by Django 4.2.7 on 2023-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='order',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='code',
        ),
    ]
