# Generated by Django 4.2.7 on 2023-12-01 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utiles.generate_code


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_rename_order_cartdetail_cart_remove_cart_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('discount', models.PositiveIntegerField(verbose_name='Discount')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='price',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=utiles.generate_code.genrate_code, max_length=10, verbose_name='Id'),
        ),
    ]
