# Generated by Django 4.2.7 on 2023-12-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_remove_cartdetail_price_orderdetail_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quntity'),
        ),
    ]
