# Generated by Django 4.2.7 on 2023-12-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_coupon', to='orders.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True, verbose_name='Total_After_Coupon'),
        ),
    ]
