# Generated by Django 4.2.7 on 2023-12-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_total_after_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_coupon', to='orders.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True, verbose_name='Total_After_Coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recived', 'recived'), ('processed', 'processed'), ('shipped', 'shipped'), ('delevered', 'delevered')], default='recived', max_length=50, verbose_name='Status'),
        ),
    ]
