# Generated by Django 4.2.7 on 2023-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='product/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
