# Generated by Django 4.2.7 on 2023-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brand_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id']},
        ),
    ]
